### ISSUE TITLE
Node.js logging

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/node-wot#1]
We need a logger given that console.log('some msg') might not be the right solution on the long run...

Are there any preferences or does anyone have experiences with one or the other solution (e.g., "log4js" or others)?

**Comment by h0ru5** [comment]
I googled and found this: https://npmcompare.com/compare/bunyan,log4js,winston

thus, go for https://github.com/winstonjs/winston

**Comment by danielpeintner** [comment]
commit https://github.com/thingweb/node-wot/commit/3f291ff30929c01919ac15061e839266c0d50217 adds winston for logging purposes
