### ISSUE TITLE
Resolve security issues flagged by npm audit

### ISSUE THREAD

**Issue by mmccool** [thingweb/node-wot#102]
NPM was recently updated to flag known security issues in dependent modules.
Unfortunately, during a recent install of node-wot I noticed that NPM flags several such security issues in the node-wot build, some critical.  

Note that a security audit can also now be invoked explicitly with “npm audit”.

We should discuss a policy on how to deal with these issues.  Currently node-wot cannot be considered secure itself as it omits other important features, such as input validation.  However, a good first step towards a more secure implementation would be to investigate the issues revealed by npm audit and decide if they are relevant and if they can be mitigated or avoided (eg by using alternative, more secure modules whenever possible, or locking particular versions without known vulnerabilities).

**Comment by mmccool** [comment]
As an update to this, I just updated to the latest version and now only 4 low-severity issues were reported by "npm audit".  Furthermore, "npm audit fix" could patch them.

**Comment by mmccool** [comment]
See https://nodesecurity.io/advisories/612 for original issues (Prototype pollution, repeated four times, via deep-extend included via multiple paths through lerna and del-cli)

**Comment by mkovatsc** [comment]
Most security issues are caused by the chai/mocha test framework, which is intended for the functionality flagged by audit. It is a dev dependencies only, though...

**Comment by mkovatsc** [comment]
Reduced the vulnerabilities by updating dependencies: https://github.com/eclipse/thingweb.node-wot/commit/511e215669948b614f27b86604d5a46ba8981e2c

Now only reports about the mocha test tools are left. But these vulnerabilities are features for unit tests. Thus closing.
