### ISSUE TITLE
RemoveProperty/Action/Event Bug

### ISSUE THREAD

**Issue by Haifalhbl** [thingweb/node-wot#104]
I have been trying to use the removeProperty/Action/Event  methods and it seems not to work since the serialized td that I am obtaining still contains the removed Interactions

**Comment by mkovatsc** [comment]
Checked and added example: https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/example-dynamic.js
Works in Eclipse Thingweb, please change to that one.
Closing.
