### ISSUE TITLE
How to use Event when i am on client side of servient ?

### ISSUE THREAD

**Issue by franckOL** [thingweb/node-wot#105]
Unable to use subscription on observable, so i need help.

Trying on EventSource example
```javascript
	// event
	thing.onEvent("onchange").subscribe(
		{
		        next: (content) => console.log("client onchange next %s", content),
			complete: () => console.log("client onchange complete")
		});
```

**Comment by mkovatsc** [comment]
At the moment, `subscribe()` is only implemented on `ConsumedThingEvent`. Still need to add it for `ConsumedThingProperty` together with the proper notifications from `ExposedThingProperty`...

Created https://github.com/eclipse/thingweb.node-wot/issues/21 and closing here.

**Comment by franckOL** [comment]
Thanks  for the answer, i see also the version 0.5.0 has more functionnalities. Have you planned to publish the node-wot package to npmjs ?

**Comment by mkovatsc** [comment]
Yes, 0.5.0 will be published once all issues with the targeted features for the Bundang PlugFest are resolved -- probably together with the Scripting API Working Drafts beginning of next month.
