### ISSUE TITLE
Servient.startScript()

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#11]
In the end we need a Servient that can run scripts from an autorun folder or by posting new scripts to it.
A startScript() function is the first step.

**Comment by h0ru5** [comment]
added untested hail-mary attempt in f46ab81e7d50e5d68aeaf26808f3e15ddced9ea1

**Comment by h0ru5** [comment]
implemented and confirmed, but needs unit-tests

**Comment by mkovatsc** [comment]
Actually, we have `runScript()` and `runPrivilegedScript()` for a while now. Closing...
