### ISSUE TITLE
Setting up node.js in Raspbian

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#14]
Let me quickly dump the info here:

```
# enlarge partition to fill SD card
sudo raspi-config
# update system
sudo apt update
sudo apt full-upgrade
# get node.js v6.9.5 LTS
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install nodejs
```

**Comment by sebastiankb** [comment]
is this also working for the IoT2xxx?

**Comment by mkovatsc** [comment]
No idea.
Might be good to take an experimental IOT2000 with node v6.9.5 and see!

**Comment by mkovatsc** [comment]
Put there was no aptitude (apt-get) on that Linux, but ipkg or opkg...

**Comment by danielpeintner** [comment]
Moved to wiki (see https://github.com/thingweb/node-wot/wiki#nodejs-in-raspbian)
