### ISSUE TITLE
targeted TD generation

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#18]
As a client, i want the thing description to contain the links relevant for me so that I can interact directly via them.

generating a thing description according to the request enables us to give out a TD that is addressable from the client and thus saves us from determination of the right ip resp. host and works even if the servient is behind reverse proxy etc.

I prepared a branch in PR #17  but would need support at least in the http server

**Comment by h0ru5** [comment]
I'll close the PR its simpler to redo those changes in the new structure than to merge.

**Comment by mkovatsc** [comment]
The problem of serializing TDs to match client needs became wider: contained bindings, language of human-readable fields, included contexts, ...

Closing here, as we moved to Eclipse and topic needs to be discussed in broader scope.
