### ISSUE TITLE
ExposedThing in node-wot always a DynamicThing?

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#21]
Not sure what happened to DynamicThing after the re-packaging:

index.d.ts: `export interface DynamicThing extends ExposedThing`
exposed-thing.ts: `export default class ExposedThing implements WoT.DynamicThing`

Does this mean in node-wot, we now only have ConsumedThings and ExposedThings, while ExposedThings are always DynamicThings?

**Comment by h0ru5** [comment]
yes, so far we only had and have DynamicThings i.e. you can add Actions, Properties etc. in a script.
That was not changed in repackaging.

**Comment by h0ru5** [comment]
to be clarified in wot scripting API
