### ISSUE TITLE
Working examples?

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#23]
I think it is quite hard for newcomers to figure out what to do with these sources. We currently have nothing that will run out-of-the-box.

I added the raspberry-servient as "privileged scripts" example, that is, a script that can import its own Node modules and starts its own Servient within its code.

We should have an autorun folder under servient-launcher that contains a "hello world" script and maybe the PlugFest Thing we envision to expose all sorts of testing resources. This script then should actually also be portable to any other WoT Servient implementation.

**Comment by mkovatsc** [comment]
I assume the `autorun` folder should go into `./node-wot-servient-launcher/dist/`. I am not sure, though, since there is no config file for wot-servient there (neither does it work at the moment :( ).

Related: should the config file really be hidden? Requires additional documentation and user awareness...

**Comment by h0ru5** [comment]
moved to /examples
