### ISSUE TITLE
prettify / coding guidelines

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#25]
An optional maintenance improvement might be to apply the [typescript coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) the codebase.

there is tooling to do checking & enforcing:
the NPM ``typescript-standard`` : https://www.npmjs.com/package/typescript-standard

initial sweep:
```
npm install -g typescript-standard

# in code dir
standard --pretty
```

to integrate:

in root project ``package.json``, add entry:
```json
{
   ...
   "scripts" :  {
        ...
         "codestyle" : "lerna codestyle"
    }
}
```

in each packages'``package.json``, add entry:
```json
{
   ...
  "devDependencies" : {
       ...
        "typescript-standard": "^0.3.14"
    }
   "scripts" :  {
         ...
         "codestyle" : "standard --pretty"
    }
}
```

**Comment by harald-mueller** [comment]
Johannes, 
if it is ok, I'll do that because this will be helpful for me as well, but i can't assign it to me.

**Comment by h0ru5** [comment]
sure, just go ahead! I cannot assign it right now either, but will add you, then it should work

**Comment by harald-mueller** [comment]
it's mostly done in branch [issue_25_coding_guidelines](https://github.com/harald-mueller/node-wot/tree/issue_25_coding_guidelines).
For the package node-wot there is a problem with the sub folders in src. Therefore it's disabled in this module.

**Comment by h0ru5** [comment]
LGTM, can you open a PR? 
Would like to merge that quickly to avoid three-way merges with such a huge hunk :)

We might have to skip the tests in node 4.2 prior to merging (because master branch requires green tests, see #31), but we could add codecheck to CI.

**Comment by h0ru5** [comment]
coding guidelines covered by #32
