### ISSUE TITLE
automated commitlog and semantic versioning

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#26]
another nice-to-have feature is an automated semver and commitlog

best practice and still lightweight  seems to be  using commitizen & conventional-changelog

https://commitizen.github.io/cz-cli/

**Comment by huerlisi** [comment]
Fully agree!

https://github.com/semantic-release/semantic-release is another candidate in this are.

**Comment by mkovatsc** [comment]
We changed to conventional commit messages.
For the changelog, I created https://github.com/eclipse/thingweb.node-wot/issues/13.
Closing here.
