### ISSUE TITLE
Problem with counter.js example

### ISSUE THREAD

**Issue by AndreMaz** [thingweb/node-wot#27]
Hi guys

I've tested the counter.js example and I've found a small problem.
I'm able to make a `GET http://10.35.0.77:8080/counter/properties/count` request without any issues.
But when I'm doing a `POST http://10.35.0.77:8080/counter/actions/increment` I'm getting the following response `"[object Promise]1"` and the log shows the following info
```
incrementing counter
0 -> [object Promise]1
counter decreased to [object Promise]1
```
Would love to help but at this moment I don't fully understand your code

**Comment by h0ru5** [comment]
Hi Andre,
thanks for trying it out! 
it seems a promise gets serializedinstead of the result of the promise... I'll have a look.

**Comment by h0ru5** [comment]
should work again now,we recently changed ``getProperty`` to async
