### ISSUE TITLE
cleaner logger integration

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#28]
I would prefer to get rid of the logger package as dependency for every package.
let's use console in all packages of the library and let the final applications then hook the console object by require-ing this snippet:

https://gist.github.com/daniloborges/7f0f0a88cd5dfb6b5af2

**Comment by mkovatsc** [comment]
The current situation with console.log redirected to logger.verbose is quite bad... breaks all command line tools and it's very hard to use test scripts at the PlugFest.

**Comment by h0ru5** [comment]
where is that done? the snippet above is not in  the code AFAIK?

**Comment by danielpeintner** [comment]
We removed the logger from node-wot as described [here](https://github.com/thingweb/node-wot/#logging) in its entirety. 

Hence, let's close this issue.
