### ISSUE TITLE
Synchronous start/stop API for servers

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#3]
The boolean return of the start/stop functions defined in the ProtocolServer interface does not make sense: the API calls to start a server are asynchronous.

http at least provides the listening property, which is set immediately and correctly. However, it is not available for node.js v4.2 and coap is missing such a feature.

For some reason the coap API replaces existing servers listening on a port. http correctly throws an error (EADDRINUSE).

**Comment by h0ru5** [comment]
we could of course let the methods return a promise.

**Comment by h0ru5** [comment]
is this related to failing test ``HTTP implementation - should start and stop a server``?
I'll put it on skip and use this issue as reference

> 1) HTTP implementation should start and stop a server:
>       AssertionError: expected -1 to equal 58080
>       + expected - actual
>       --1
>       +58080
>       
>       at HttpTest.should start and stop a server (test/ProtocolsTest.js:23:48)
>       at Context.<anonymous> (node_modules/mocha-typescript/index.js:157:47)

**Comment by mkovatsc** [comment]
Fixed in c7fdbaf79920ee10957b8fad428bcb47866a725c
