### ISSUE TITLE
uriToOptions Method is duplicate in several places

### ISSUE THREAD

**Issue by harald-mueller** [thingweb/node-wot#30]
uriToOptions(uri) Method is duplicate in several places
there is also already a not fully implemented fragment in Helpers.

we should use the Helpers one in all places.

**Comment by h0ru5** [comment]
it is assumable that they target different option objects

**Comment by mkovatsc** [comment]
There are now only two versions: one for HTTP, one for CoAP, and they produce different option objects.
Closing.
