### ISSUE TITLE
commandline runner attempts to run all kinds of files

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#37]
the `wot-servient` cli runner tries to run all files, should restrict to '*.js'

**Comment by rzr** [comment]
Actually It looks that filtering is already done (along dot files) in:

node-wot/packages/node-wot-servient-examples/src/command-line-tool/wot-servient.ts

`
  // unhidden .js files
        let scripts = files.filter( (file) => {
            return (file.substr(0, 1) !== "." && file.slice(-3) === ".js");
        });
// (...)
        runScripts(srv, scripts.map(value => path.join(scriptDir, value)));

`

**Comment by danielpeintner** [comment]
Correct. I think we can close this issue.
