### ISSUE TITLE
configuring protocol bindings in the command line runner

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#38]
To extend or generally configure the command line runner, we forsee to look for a `wot-servient.conf.json` in the directory.

This should in future also be used to include protocol adapters.
if the json file includes the entries: 
```
"servers" : [
   "node-wot-protocols-coap-server"
],
"clients" : [
    "node-wot-protocols-coap-client"
]
```

then the cli should attempt to require() them and add them to the servient

**Comment by mkovatsc** [comment]
Moved to https://github.com/eclipse/thingweb.node-wot/issues/14.
Closing here.
