### ISSUE TITLE
TD tools must apply proper URI arithmetic

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#4]
Currently the base and href strings are only checked for '/'.
If an href starts with '/' it must be treated as absolute path, replacing the path of base (but still use scheme, host, etc.).

Try to use "url" module or other tools to implement proper URI arithmetic.

**Comment by sebastiankb** [comment]
hmm, actually, this should already work. I will check this

**Comment by sebastiankb** [comment]
I fixed the issue by the usage of the url module. Version is committed.

**Comment by mkovatsc** [comment]
Works now, also covered by unit test.
