### ISSUE TITLE
TD parser should be tolerant with arrays and strings

### ISSUE THREAD

**Issue by sebastiankb** [thingweb/node-wot#42]
Currently, we allow only TDs that use arrays in the @context field: 

`"@context":["http://...`

The TD parser crashes when only a (valid) string is provided:

`"@context":"http://...`
 
Both variants should be possible --> a pre-processing has to be done before the TD is passed to TypedJSON

**Comment by danielpeintner** [comment]
In the Current Practices document all examples use array for @context. There is only one exception (Example 6)

I think it would be beneficial for implementation complexity and also interoperability to specify whether we should really allow for a single string if an array is possible. Shall we discuss this in the WoT TD task force?

It would be much easier to say that IF an array is possible an array MUST be used.

Any thoughts?

**Comment by mkovatsc** [comment]
We dropped the convention for forcing arrays in the WG to be compatible with common JSON-LD library outputs. Closing.
