### ISSUE TITLE
error in "npm run bootstrap"

### ISSUE THREAD

**Issue by amitnagar19** [thingweb/node-wot#45]
Hello, I am trying to run bootstrap and i am getting following error:

 lerna bootstrap

lerna info version 2.0.0-rc.5
lerna info versioning independent
lerna info Bootstrapping 13 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna ERR! execute Error: ENOENT: no such file or directory, stat 'C:\Users\amit\node-wot\packages\node-wot\dist\command-line-tool\wot-servient.js'
lerna ERR! execute     at Error (native)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: ENOENT: no such file or directory, stat 'C:\Users\amit\node-wot\packages\node-wot\dist\command-line-tool\wot-servient.js'
lerna ERR! execute     at Error (native)
lerna ERR! execute   errno: -4058,
lerna ERR! execute   code: 'ENOENT',
lerna ERR! execute   syscall: 'stat',
lerna ERR! execute   path: 'C:\\Users\\amit\\node-wot\\packages\\node-wot\\dist\\command-line-tool\\wot-servient.js' }

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-wot-root@0.0.2 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-wot-root@0.0.2 bootstrap script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-wot-root package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-wot-root
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-wot-root
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\amit\node-wot\npm-debug.log

**Comment by danielpeintner** [comment]
Note: This issue seems to exist on Windows machines only and it relates to the path TypeScript files are transcompiled to.
For example on Linux it just works fine...

**Comment by danielpeintner** [comment]
A temporary solution to fix that so far is to call "tsc.cmd" manually.

You can find it in the folder the "node_modules\\.bin"

Afterwards you can call "npm run bootstrap" again and it should work....

**Comment by mkovatsc** [comment]
Doesn't work also after calling `tsc`.

I don't understand why lerna wants to touch `dist` files at all (i.e., `packages\node-wot\dist\command-line-tool\wot-servient.js`).

**Comment by danielpeintner** [comment]
The "new" node-wot package structure should resolve this issue.

Please feel free to report and reopen the issue if it still fails...
