### ISSUE TITLE
CORS  / serialization format with counter.js and webui

### ISSUE THREAD

**Issue by Stoakes** [thingweb/node-wot#46]
Hi,

I tried to use the counter example with the thingweb-webui. It eventually worked but I had to tweak several stuff to make it works. Here is a quick feedback that might interest you.

I used the webui with Firefox and could not  make an action call. The error was `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://139.xx.xx.xxx:8080/counter/actions/increment. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).` 

I turned [node-wot-protocols-http-server/src/http-server.ts#L124](https://github.com/thingweb/node-wot/blob/master/packages/node-wot-protocols-http-server/src/http-server.ts#L124) to `res.setHeader('Access-Control-Allow-Headers', 'authorization, content-type');` and it fixed the issue.

Then I encountered the issue : 

```
/home/node-wot/packages/node-wot-content-serdes/dist/content-serdes.js:79
            throw new Error("Unsupported serialisation format: " + content.mediaType);
            ^

Error: Unsupported serialisation format: application/json;charset=utf-8
    at ContentSerdes.bytesToValue (node-wot/packages/node-wot-content-serdes/dist/content-serdes.js:79:19)
    at ActionResourceListener.onInvoke (node-wot/packages/node-wot/dist/resource-listeners/action-resource-listener.js:25:55)
    at IncomingMessage.<anonymous> (node-wot/packages/node-wot-protocols-http-server/dist/http-server.js:148:36)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

I turned [node-wot-protocols-http-server/src/http-server.ts#L133](https://github.com/thingweb/node-wot/blob/master/packages/node-wot-protocols-http-server/src/http-server.ts#L133) into `let mediaType = ContentSerdes.DEFAULT;` to get the default value every time and it was solved.

BTW the quickstart example in the readme is confusing. It doesn't seems to work if you don't install packages globally. So may turn the line `wot-servient` into `node ../../packages/node-wot/dist/command-line-tool/wot-servient.js` 

Antoine Beyet,

**Comment by h0ru5** [comment]
Hi Antoine,

thanks for the feedback.
You are addressing 3 Issues: 
1) CORS - totally right, and it makes sense for me to do CORS headers as default as you describe in your fix. 

2) media type & charset (e.g. `application/json;charset=utf-8`) brakes the ContentSerdes - should be fixed with commit ef63e6df0fa7bde49d6587bc3b9643daf5797d55, can you check if you have the HEAD rev? if it still occours, we should put an issue up.

3) Quickstart guide: it assumes you resp. lerna ran the `npm link` in wot-servient, which will install/symlink the package globally. This is one of many issues that will be gone when we publish to npmjs.

**Comment by Stoakes** [comment]
Hi,

As for issues : 

 1. FYI I ran into another issue when I tried to set the count value from the webUI (PUT request) : 
   ```
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://139.xx.xx.xxx:8080/counter/properties/count. (Reason: Did not find method in CORS header ‘Access-Control-Allow-Methods’).
   ```
It should be the same with a DELETE request but I could not test from the webUI.

 2. Indeed, it works. Thanks

 3. Ok. Just by curiosity, have you already planned a date ?

Everything is fine for me. I let you close the issue now or later according to your workflow.

Bye

**Comment by h0ru5** [comment]
> FYI I ran into another issue when I tried to set the count value from the webUI (PUT request) 

This is related to how a browser checks for same origin policy: it sends an OPTIONS request (pre-flight request), this should have the CORS headers in the rsponse and then the actual request, which also needs the CORS headers in the response.

**Comment by mkovatsc** [comment]
I fixed this partly by adding all methods to Access-Control-Allow-Methods.

Firefox apparently does not support the wildcard for Access-Control-Allow-Headers, so I added `content-type` to fix the WebUI usage. Need to add `authorization` as well to close this issue.

Are there any other header fields we need? Maybe we need to collect them along the road...

**Comment by mkovatsc** [comment]
Added `authorization`, closing.
