### ISSUE TITLE
Where to convert to/from Buffer

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#5]
@h0ru5 ClientTests are failing. It is not clear to me where in the test you expect to handle the Buffer passed to and from the ProtocolClient interface...

servient-example.ts works as expected from a WoT script...

**Comment by mkovatsc** [comment]
I converted this to a "design question" and marked/will mark relevant places in the code with TODO #5
The question is where and how to convert from the scripting object to the Buffer expected by the ProtocolClient.

**Comment by h0ru5** [comment]
we should look more closely to seperate:
(a) the serialization (e.g. json) from 
(b) the type (the object that is expected)

I sketched out the architecture in 85ed929126dffb4ede7e952feaf852b9165fb30d:
a singleton SerDes (serialzer-deserializer) that can support pluggable codecs for JSON, EXI, XML, mail pigeons and morse code.

The type checking could be done in similar fashion or even in the same class

**Comment by mkovatsc** [comment]
Yes, that's what I am talking about:
"serialization": Buffer + MediaType  => passed to/from ProtocolClient
"type" or rather "scripting object": object => passed to/from Thing impls in WoT script
"valueType": for now JSON Schema => defined in TD
