### ISSUE TITLE
module typescript@2.4.1 breaks tests

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#50]
I had to tie down the version to typescript@2.3.2 to get the unit tests working again. There might be a higher working version, but the latest 2.4.1 does not work.

First guess: Seems to be some incompatibility between the latest typescript and mocha or chai.

**Comment by mkovatsc** [comment]
It is working for now, but we should be able to use newer versions.

**Comment by danielpeintner** [comment]
Currently we tie down node-wot to given packages&versions to avoid such issues.

For example  typescript is currently set to 2.5.2
