### ISSUE TITLE
TD serializer converts array to object

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#51]
In the JSON Schema part, the `required` array is serialized to:
```
"required": {
    "0": "prop1",
    "1": "prop2"
}
```

**Comment by sebastiankb** [comment]
the correct version should be "required": ["prop1", "prop2"] , right? 

can you give me the TD file or a link where this bug occurs?

**Comment by mkovatsc** [comment]
Has been fixed. Closing.
