### ISSUE TITLE
Add a parameter to deactivate handlers on ConsumedThing.setProperty

### ISSUE THREAD

**Issue by Stoakes** [thingweb/node-wot#53]
Hello

I'm working on an cooperation between node -WoT and a MQTT framework.  In a word, you have several node-wot nodes exposing their HTTP API and also listening to a MQTT network.
The state of a node can be changed through a call to the HTTP API (that change is then retransmitted on the MQTT network) or a change event can be received from an another node through MQTT and applied to the node using the scripting API.

It's working with actions (When a change arrive from MQTT I add a specific value to the parameter sequence and the handler check if that value exists or not and adapt its behavior).

However I have an issue with properties.  The situation is:  when a change is received by the HTTP API, a listener defined with `ExposedThing.onUpdateProperty` takes the new value and sends it on the MQTT network.  
But when a change arrives through MQTT, I call `ConsumedThing.setProperty` to change the local value. Then we run into an infinite loop because I have no way to stop handlers to emit a new change event on the MQTT network.

We can imagine a new boolean parameter (set by default to true) to setProperties to define if handlers have to be called or not.

Does that seems ok for you ? Would you merge a PR adding this feature ?

Antoine Beyet,

**Comment by danielpeintner** [comment]
Hi Antoine,

node-wot is meant to become one implementation of the W3C WoT Scripting API (see https://w3c.github.io/wot-scripting-api/)
MQTT is definitely of interest there.

Having said that, if you encounter issues with the current API (https://w3c.github.io/wot-scripting-api/#idl-def-consumedthing) you might want to create an issue on the WoT Scripting API (https://github.com/w3c/wot-scripting-api/issues) issue tracker.

The ultimate goal is to allow the Scripting API to work with any protocol...

**Comment by mkovatsc** [comment]
Different protocols should not be handled differently at the Interaction level. Whether a change comes from HTTP or MQTT must not make a difference. The adaption is usually done in the protocol binding server part and then passed to the ResourceListener.

Since there has been no feedback for a year, I am closing.
