### ISSUE TITLE
Renaming for better conventions

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#6]
I did some renames...
Some are clear TD.TDInteraction -> TD.Interaction
Some are minor like ./tdparser -> ./td-parser

Some are major like ./servedthing -> ./exposed-thing and ./proxything -> ./consumed-thing
However, why served and proxy..?

 @h0ru5 @sebastiankb I hope that's fine..

**Comment by mkovatsc** [comment]
I now also renamed the TD enums...

**Comment by h0ru5** [comment]
OK for me.
regarding enums: it would be good whenever we introduce enums that have string-based counterparts to have the enums string-based.
or when using numeric ones, to provide functions to translate them

**Comment by mkovatsc** [comment]
I still have to figure out how the enum MediaType was intended.
But I guess you mean this:
```
/** Internet Media Types */
export enum MediaType {
    JSON = <any>"application/json",
    XML = <any>"application/xml",
    EXI = <any>"application/exi"
    /* TODO: add more media types here */
}

/** Interaction pattern */
export enum InteractionPattern {
    Property = <any>"Property",
    Action = <any>"Action",
    Event = <any>"Event"
}
```

**Comment by sebastiankb** [comment]
Also OK for me.  Please note: I will move the Interaction class into a separate file since JS do note support inner class definition. 
@mkovatsc I was not aware of this enum definition. I will update the enums.

**Comment by mkovatsc** [comment]
Enums are already changed.
Also the "inner classes" actually work quite nicely now:

```
import ThingDescription from "./td/thing-description";
import * as TD from "./td/thing-description";
...
let newProp = new TD.Interaction();
```
So it also gives you the nice namespacing with TD.

**Comment by sebastiankb** [comment]
a real inner class is defined in that way:
class TD {
...

 class Interaction {
 ...
 }
}

However, this is not allowed in JS. However, we can keep as it is. Is just a nice to have....

**Comment by sebastiankb** [comment]
I close this issue.
