### ISSUE TITLE
Check-in package-lock.json?

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/node-wot#60]
So far we did not check-in package-lock.json.

I do get the message `created a lockfile as package-lock.json. You should commit this file.`

Any rational for not checking-in this file or put differently any downside if we still don't do that in the future?

**Comment by mkovatsc** [comment]
`package-lock.json` is not part of the publication to NPM, so bugs in dependencies might only appear after a release, which of course is bad. Furthermore, `package-lock.json` reliably breaks `npm link`.

To my current understanding, `package-lock.json` only makes sense for application projects, but not library modules, which most node-wot packages are.

Hence, we do not check in `package-lock.json` and even have the `npm run unlock` target to get rid of them. The ways I found to suppress their generation did not work reliable so far; maybe good for the future.

Closing.
