### ISSUE TITLE
NPM Packages Prefix

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/node-wot#66]
Before publishing node-wot packages to NPM we might consider agreeing on a common prefix like "@wot/..." similar to "@reactivex/" (see https://www.npmjs.com/search?q=@reactivex)

TODO: Check how this prefixing is done for NPM

1. https://docs.npmjs.com/getting-started/scoped-packages OR
2. `npm publish --tag <tag>` might do the job

**Comment by huerlisi** [comment]
Using scopes is a good practice nowadays;-)

Let's hurry or the nice `@wot` will be taken;-)

**Comment by bufferoverflow** [comment]
@huerlisi please register and hand it over to @mkovatsc tomorrow

**Comment by mkovatsc** [comment]
`@node-wot` is now registered and will be used by the upcoming 0.3.0 FPWD release.
