### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by egekorkan** [thingweb/node-wot#68]
I will create a better documentation, I'm creating this issue as a reminder for myself :) Can you assign it to me please?

**Comment by egekorkan** [comment]
I wasn't really aware of the new API coming up, should I wait for it to finalize or should I write a doc by taking into account the new specifications https://w3c.github.io/wot-scripting-api/#introduction

**Comment by danielpeintner** [comment]
Hi,

waiting for the upcoming API makes definitely sense!

I am not sure how you planned to create the documentation.
Just one idea. Maybe it makes sense  to use [JSDoc ](http://usejsdoc.org/)which is at least partly [supported](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript) in TypeScript.

**Comment by mkovatsc** [comment]
@egekorkan What is the status? I created https://github.com/eclipse/thingweb.node-wot/issues/16 and closing here.
