### ISSUE TITLE
Prefer expect() over should in chai tests?

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#7]
It was a bit annoying that you have to call should() once to make it work.
Furthermore, I find it a bit confusing to switch between both styles a lot.

expect() seems to be a bit more powerful than should (does not conflict in special cases, adjustable log message).

Thus, I would propose that we just use expect() in tests. WDYT?

**Comment by h0ru5** [comment]
I would just leave it up to personal preference. Not very attached to either one, but sometimes its nicer one way or the other.

**Comment by mkovatsc** [comment]
Okay, I guess it gets better once the unit tests are in place and just work :P

**Comment by mkovatsc** [comment]
@sebastiankb, @vcharpenay, @danielpeintner 
Then maybe just as info for you: when you write new tests and use `should`, remember to make a call `should()` after importing it :)
