### ISSUE TITLE
Belated Servient start

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/node-wot#70]
Due to whatever reason the HTTP Server does not start right away.

To reproduce the failure run in one shell
`node packages\node-wot-servient-examples\dist\command-line-tool\wot-servient.js  examples\scripts\counter.js`
and in another shell
`node packages\node-wot-servient-examples\dist\command-line-tool\wot-servient.js  examples\scripts\counterClient.js`.

The counter client needs to be started a second time to _actually_  start the server (see https://github.com/thingweb/node-wot/blob/master/packages/node-wot-protocol-http/src/http-server.ts#L80).

**Comment by mkovatsc** [comment]
I also observed this behavior. It seems as if it is stuck in the event loop and need one external event to go through...

**Comment by danielpeintner** [comment]
fixed by https://github.com/thingweb/node-wot/commit/666e16d13a154d6584a87f02e7ece6bd49f45c68
