### ISSUE TITLE
Burlingame PlugFest API

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#71]
0.3.0-SNAPSHOT.4 currently has the mix of ThingBuilder (`addXXX(ThingXXXInit)`) and RequestHandler API. I will try to align it by fixing `ThingPropertyInit` with the PropertyHandler `onWrite`.

**Comment by danielpeintner** [comment]
fixed by https://github.com/thingweb/node-wot/commit/b1e520cc0eff2c349328d0e63e3b7ab2078e08da
