### ISSUE TITLE
Need for "pattern" in thing-description model ?

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/node-wot#74]
I wonder why `pattern` is there in [`thing-description`](https://github.com/thingweb/node-wot/blob/master/packages/node-wot-td-tools/src/thing-description.ts) model? The same information is in `semanticTypes`?
`pattern` =!= `semanticTypes[0]`

Or do we foresee this difference w.r.t. Scripting API to have a separate container once for the actual interaction pattern (Property, Action, and Event) and another one for sematicTypes?

Another question to me is also why the enumerated values of `InteractionPattern` are declared as any. Why not simply string?

**Comment by mkovatsc** [comment]
It is not ensured that index 0 always has the Interaction Pattern class...
Also it is more convenient and explicit internally.

Hopefully simplified soon anyway... ;)

**Comment by mkovatsc** [comment]
"Simplified away"!
Closing.
