### ISSUE TITLE
Adding SemanticTypes

### ISSUE THREAD

**Issue by amitnagar19** [thingweb/node-wot#76]
Is it possible to add semantic annotations to Interactions while exposing a thing?

 Also the add property function takes name,output type and initial value as parameters. So , Is it possible to add semantic annotations also?

**Comment by danielpeintner** [comment]
Hi @amitnagar19.

We started to update node-wot according to https://github.com/w3c/wot-scripting-api/issues/82 which allows you to add `semanticTypes` in `ThingPropertyInit` (see branch https://github.com/thingweb/node-wot/tree/PlugFest-Prague-2018).

The new API is not fully done yet given that the TD serialization is planned to change also. Stay tuned!

**Comment by amitnagar19** [comment]
Hello @danielpeintner,

I tried adding sematicTypes in a property, it does not show any error but
neither is it reflected on the exposed thing. The thing description looks
the same. Am I missing something.

Thanks

**Comment by danielpeintner** [comment]
Hi @amitnagar19 

> The new API is not fully done yet given that the TD serialization is planned to change also. Stay tuned!

As mentioned it is not fully implemented yet. You need to wait bit.

**Comment by mkovatsc** [comment]
This was fixed with the v0.4.0 release version.
With the new Simplified TD, it is even easier to do so: Go to https://github.com/eclipse/thingweb.node-wot
Closing.
