### ISSUE TITLE
Counter example from the readme does not work

### ISSUE THREAD

**Issue by junjchen** [thingweb/node-wot#79]
Hi Guys,

Good day.

I am new to node-wot but it looks like the counter example in the readme is no longer available? Seems web-servient.ts is deleted from the project. Would you mind to update the readme?

Thanks.

**Comment by mkovatsc** [comment]
Might have been a work-in-progress issue.

`wot-servient`, not `web-servient`, is an executable from the `cli` package.
Counter example is also under `examples/scripts/`.

Definitely solved in https://github.com/eclipse/thingweb.node-wot. Closing.
