### ISSUE TITLE
Roundtrip test is broken

### ISSUE THREAD

**Issue by h0ru5** [thingweb/node-wot#8]
the roundtrip tests breaks because of optional fields
setting to skip

```
> 1) TD parsing/serialising should return same TD in round-trip:

      AssertionError: expected { Object (@context, @type, ...) } to deeply equal { Object (@context, @type, ...) }
      + expected - actual

         "@context": [
           "http://w3c.github.io/wot/w3c-wot-td-context.jsonld"
         ]
         "@type": "Thing"
      -  "base": [null]
         "interactions": [
           {
             "@type": [
               "Property"
               "valueType": {
                 "type": "number"
               }
             }
      +      "writable": false
           }
         ]
         "name": "MyTemperatureThing"
       }
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at TDParserTest.should return same TD in round-trip (test/TDParseTest.js:30:44)
      at Context.<anonymous> (node_modules/mocha-typescript/index.js:157:47)
```

**Comment by mkovatsc** [comment]
Decorated and present writable is missing after TypedJSON.parse().
Decorated and absent base is set to null and cannot be deleted.

Bug in TypedJSON?

**Comment by sebastiankb** [comment]
Is the TD correct. I cannot see any link / href information.

**Comment by mkovatsc** [comment]
Note that the test output just prints 4 lines before and 4 lines after the "problem line". So there is a printing discontinuity between "Property" and "valueType"...

**Comment by mkovatsc** [comment]
Check the td-parser logging output. For some reason, only a subset of members are actually in the class... no idea why.

**Comment by sebastiankb** [comment]
ok, I will check this

**Comment by sebastiankb** [comment]
absent of the base is fixed by a workaround. Version is committed. 

Regarding writable: When I run my own test by example/td-example.tc the writable key occurs with the right values. Seems to be some side effects. Keep following this.

**Comment by mkovatsc** [comment]
This is because I implemented a workaround in td-parser.ts:
```
// FIXME #8 helps to pass TDParseTest
            if (interaction.writable===undefined) {
                logger.silly(`parseTDString() setting implicit writable to false`);
                interaction.writable = false;
            }
```

**Comment by mkovatsc** [comment]
Looks like TypedJSON cannot handle the custom-type member TD.Interaction... @type is also not converted to semanticTypes.

**Comment by sebastiankb** [comment]
Below is the output of the example/td-example.tc test. Is shows always the right writable value (first TD writable = true, second TD writable = false):

TD as Object:
 Thing name: MyTemperatureThing
 Interaction name: temperature
 Interaction link: coap://mytemp.example.com:5683/temp
 Is writable: true

TD as JSON Sting:
{"@context":["http://w3c.github.io/wot/w3c-wot-td-context.jsonld"],"@type":"Thing","interactions":[{"@type":["Property"],"name":"temperature","outputData":{"valueType":{"type":"number"}},"writable":true,"links":[{"href":"coap://mytemp.example.com:5683/temp","mediaType":"application/json"}]}],"name":"MyTemperatureThing"}

Test URI resolutions:
 Thing name: MyTemperatureThing
 Interaction name: temperature
 Interaction link: coap://mytemp.example.com:5683/temp
 Is writable: false

**Comment by mkovatsc** [comment]
It might be because an undefined writable is similar to a writable:false.

When you put writable:true in the test string it parses correctly and the member is there...

So the workaround with implicit wratable works.

Open problem is still that the inner class is coverted to a simple object. I have a workaround for that, too.
