### ISSUE TITLE
Counter.js not working on latest build

### ISSUE THREAD

**Issue by amitnagar1** [thingweb/node-wot#84]
I installed this new node-wot and counter.js is not working for me.
Error:
WoTImpl producing new ExposedThing
Trace: error building CLI Management Thing: TypeError: console.debug is not a function
    at /node-wot-master/packages/cli/dist/default-servient.js:83:25
    at process._tickCallback (internal/process/next_tick.js:109:7)
WoT-Servient cannot start: console.debug is not a function

**Comment by danielpeintner** [comment]
FYI: console.debug requires node version 8+
