### ISSUE TITLE
TD generator produce a non valid security container

### ISSUE THREAD

**Issue by sebastiankb** [thingweb/node-wot#85]
Discovered in #81. It seems that node-wot generates always a non valid security container of a servient:

```JSON
{
    "@context": ["https://w3c.github.io/wot/w3c-wot-td-context.jsonld"],
    "@type": ["Thing"],
    "name": "TestThing",
    "security": {"description": "node-wot development Servient, no security"},
   
}
```

1. If no security is used node-wot should not generate this container
2. If security is required then a JSON array should be generate as defined by the TD spec

**Comment by mkovatsc** [comment]
Fixed in 0.5.0 snapshot at Eclipse. Closing.
