### ISSUE TITLE
empty base string produces url without the protocol

### ISSUE THREAD

**Issue by egekorkan** [thingweb/node-wot#98]
An empty string, i.e. "", produces a url to fetch interaction that doesnt have a protocol.

Images for TD and base URI

![image](https://user-images.githubusercontent.com/20195407/37877186-60e38966-3057-11e8-9375-9f8ea89924f3.png)

![image](https://user-images.githubusercontent.com/20195407/37877165-13c45764-3057-11e8-9c3b-ec2de2ace37e.png)

**Comment by mkovatsc** [comment]
Does not happen anymore with 0.5.0 snapshots.
Closing.
