### ISSUE TITLE
Cannot get TD of an ExposedThing with COAP (+ possible fix)

### ISSUE THREAD

**Issue by nsorin** [thingweb/node-wot#99]
Hello,

I am using the lib to expose dummy things in my research. When trying to expose a thing using only a COAP server, I noticed it is not possible to get the TD through COAP because the application/ld+json format is not registered as a possible Content-format in COAP (it is indeed not present in the registry described in the RFC: https://tools.ietf.org/html/draft-ietf-core-coap-18#section-12.3).

So when requesting the TD using COAP, I get:

```Got response: 5.00 Unknown Content-Format: application/ld+json```

Which is expected. A simple fix would be to use the ```registerFormat``` function of the coap library used in node-wot to assign an identifier to the application/ld+json format. For the purpose of my research, I had to edit the dist file (```coap-server.js```) directly by adding the following line right after the import:

```javascript
coap.registerFormat('application/ld+json', 55); // 55 is arbitrary here, a better identifier should be use to conform with the RFC
```

I would suggest registering the format properly in the CoapServer source so the TD can be reached using COAP.

Thank you for reading this issue.

**Comment by danielpeintner** [comment]
I think this issue has been captured already (see https://github.com/thingweb/node-wot/issues/97).

**Comment by mkovatsc** [comment]
Not really, it is a problem of the `coap` module, which also has a registration for Content-Format -- the numeric identifier of a media type + encoding.

We can use this to pick the numbers: https://svn.tools.ietf.org/svn/wg/core/mediatypes.txt, so 2100 for ld+json.

I will work on a fix in https://github.com/eclipse/thingweb.node-wot

**Comment by mkovatsc** [comment]
Fixed in https://github.com/eclipse/thingweb.node-wot/commit/cd216039acfea1e500984987282b07c22a31fa47 at Eclipse.
Closing.
